### PR TITLE
Add httpclientmodule imports to all test spec files, add skeletons for additional tests

### PR DESCRIPTION
**Pull request by nairnairnair**
Description
Add httpclientmodule imports to all test spec files, add skeletons for additional tests

Fixes
12/14 tests currently pass as a result of adding these imports (up from 4/14). Most of these tests are fairly simple and I would like to request help coming up with a few others (unit testing in Angular is really, really hard). Please review these tests and suggest any that you think would be good to include.

[x] Bug fix (non-breaking change which fixes an issue)
Checklist:
 [x] My code follows the style guidelines of this project
 [x] I have performed a self-review of my code
 [x] I have made corresponding changes to the documentation (as needed)

### CODE REVIEW

**Review by mayakappen — COMMENTED** [review]
That's good that you got those passing. I need to do more research on Jasmine but maybe we could test our services? Either that or find a way to test the components showing up on the pages. We only need to have 25% coverage and I think we technically already have that with these current tests but I want to make sure so I definitely agree we should add a few more.

**Comment by nairnairnair** [comment]
>maybe we could test our services? Either that or find a way to test the components showing up on the pages. 

Yeah, that's sort of what I was thinking too. We'll have to get the testbed involved to see if things are showing up on the page itself, it looks like. So like, maybe service testing would actually be easier despite seeming scarier. Just not sure which one we want to move forward with. Let me know if you come to a conclusion of which one you want to go after and we'll get on it. Also, do you notice anything obviously off about our two failing tests? I'm sure they're just not set up properly but any insight you can offer would be appreciated.

**Comment by mayakappen** [comment]
I mean one of them is literally testing for a string that isn't there anymore so I assume you're talking about the other one. I don't think getting testbed involved is that hard, we already have an example of it in the test I just mentioned. You create a component and then assign it to a variable and check within that instance of the component for the element in question. I think it'd be way easier to do that than testing the services.

**Comment by nairnairnair** [comment]
Oh, wow, that makes sense. Yeah let's definitely create some of those, then. Would be good to make sure everything is showing up on the page correctly.

**Comment by mayakappen** [comment]
Ok, merging this in now. Let's write some more tests.

**Comment by mayakappen** [comment]
Oops lol, did not mean to close this.

**Pull request merged**
